#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}
menuentry "System restart" {
	echo "System rebooting..."
	reboot
}
if [ "${grub_platform}" == "pc" ]; then
	menuentry "Microsoft Windows 7" {
		insmod part_msdos
		insmod ntfs
		insmod search_fs_uuid
		insmod ntldr
		search --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 064E47704E475817
		ntldr /bootmgr
	}
fi
